# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
google_analytics: dbyll
title: Davis Owen

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Welcome

description: Davis Owen
author:
  name: Davis Owen
  email: sdowen12@gmail.com
  github: https://github.com/DavisOwen
  linkedin: https://www.linkedin.com/in/davis-o-88726b111/
  bio: My Blog

categories_path: categories.html
tags_path: tags.html

# set it as url of an image
#sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
