backend:
    name: git-gateway
    branch: master

publish_mode: editorial_workflow
media_folder: "assets/media"
collections:
    - name: "post"
      label: "Post"
      folder: "_posts"
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Categories", name: "categories", widget: "list"}
          - {label: "Tags", name: "tags", widget: "list"}
          - {label: "Description", name: "description", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
